### ISSUE TITLE
Runout Sensor on silent board 4.2.7

### ISSUE THREAD

**Issue by PaNaVTEC** [Flawioo/Creality-Ender-3-board-v4.2.7#4]
Hey @Flawioo I was following this guide and this post: https://github.com/MarlinFirmware/Marlin/issues/19029#issuecomment-680974552 of yours, I have everything working except the runout sensor, do you know the wiring of the 3 pin jst connector of the stock 4.2.7 board to connect a single microswitch? I tried to connect the regular `C, NC` pins of the microswitch to different positions of the silent board switch but I cound't make it work. Something like this: 

<img width="367" alt="samplewiring" src="https://user-images.githubusercontent.com/837104/93689296-71a37980-facd-11ea-90a7-23b867a7b38b.png">

Any help is appreciated, thanks :)

**Comment by PaNaVTEC** [comment]
Lol, just wiring the 2nd pin as well started to work I thought the two on the sides were the only ones needed, but nop. Anyway, it works, maybe it helps someone 😁

**Comment by Flawioo** [comment]
Hi @, You got the point, just two pins are enough. 
Best Regards

**Comment by ShaunTheBaa** [comment]
I dont understand, how did you fix it? I have a micro switch wired exactly like the picture above and it doesn't work, M119 just always shows it as triggered. What 2nd pin are you talking about?

**Comment by k0jara** [comment]
Switch has 3 pins:
g - ground
c - closed
nc - not closed

by default, the connection ground/closed is closed, ground/not_closed is open
triggering the switch, these states change: gound/closed is open, ground/not_closed is closed

i might have mixed it up, but you get the idea how the switch works.

**Comment by docwoelle** [comment]
> I dont understand, how did you fix it? I have a micro switch wired exactly like the picture above and it doesn't work, M119 just always shows it as triggered. What 2nd pin are you talking about?

You have to use a pullup resistor (10k) between V (VDD) and S. The switch (NO and C) must be between G and S.
This means, the NO (normally open) is closed when the switch is pressed (filament is present).
In Marlin, set "FIL_RUNOUT_STATE" to "HIGH". When filament is absent, the S pin (signal) will be pulled to HIGH by the resistor. If filament is present, it will be LOW by the switch to G (ground).

**Comment by jx2014** [comment]
The idea is to either send 3.3V to the Signal pin (input logic High), or ground the Signal pin (input logic Low).
Therefore, the Signal pin from the 4.2.7 PCBA must go to 'Common' of the micro switch. 

You never ever want to connect the Ground pin from the 4.2.7 PCBA to the Switch 'Common' pin, doing so will short circuit the 3.3V output from the main board and damage it.

**Comment by jx2014** [comment]
This is the default setting in `Configuration.h`

>#if ENABLED(FILAMENT_RUNOUT_SENSOR)
  #define FIL_RUNOUT_ENABLED_DEFAULT true // Enable the sensor on startup. Override with M412 followed by M500.
  #define NUM_RUNOUT_SENSORS   1          // Number of sensors, up to one per extruder. Define a FIL_RUNOUT#_PIN for each.
  #define FIL_RUNOUT_STATE     LOW        // Pin state indicating that filament is NOT present.
  #define FIL_RUNOUT_PULLUP               // Use internal pullup for filament runout pins.
  //#define FIL_RUNOUT_PULLDOWN           // Use internal pulldown for filament runout pins.
  //#define WATCH_ALL_RUNOUT_SENSORS      // Execute runout script on any triggering sensor, not only for the active extruder.
                                          // This is automatically enabled for MIXING_EXTRUDERs.


As you can see, the Run state is by default `Low`, if the switch is `Open`, the mainboard input signal pin should get a `Low` input signal, in other words, the ground pin from the mainboard should be connected to the signal pin by the switch mechanism. 

When the filament is present, the roller switch is depressed, the mainboard input signal pin should get a `High` input signal, in other words, 3.3V pin from the mainboard should be connected to the signal pin by the switch mechanism. However, there is a `#define FIL_RUNOUT_PULLUP`, which means the signal pin, if nothing is connected to it, will remain `High` state due to a internal pull up resistor that's connected to the power supply, in other words, you don't really need to connect the 3.3V pin to the swtich at all.

some terms to describe the three pins of the roller switch: 
NC. Normally Closed, when the roller is relexed, the NC pin is shorted to the Common pin while NO pin becomes open.
NO. Normally Open, when the roller is depressed, the NO pin is shortted to the Common pin while NC pin becomes open.
C.    Common.

**Comment by jonathanpere404** [comment]
![photo1686026220](https://github.com/Flawioo/Creality-Ender-3-board-v4.2.7/assets/43252650/022d10c7-b554-46d4-a9e0-a10da2811e73)
![photo1686026239](https://github.com/Flawioo/Creality-Ender-3-board-v4.2.7/assets/43252650/95793dcc-b4c3-491f-aedc-3ceb462d9f63)
![image](https://github.com/Flawioo/Creality-Ender-3-board-v4.2.7/assets/43252650/7419da33-a2fd-4a6f-889b-3612f0c622fd)

this is how i did it.

**Comment by aldi1502** [comment]
Hi. I'm new at this my board is a v2 4.2.2 could you send me the script and how exactly to insert it

**Comment by aldi1502** [comment]
is there a particular place to put it in the program

**Comment by Flawioo** [comment]
Hi @aldi1502 sorry but I can't help you with v4.2.2 board.

**Comment by aldi1502** [comment]
ok thanks

**Comment by yw4z** [comment]
@jonathanpere404 do you have any issues on this method. i'm planning to use this on klipper for klicky probe. but can't find any info. also i got 4.2.7 board that has separate slot for BLTOUCH and i'm not sure can i connect an micro switch to it's socket

**Comment by ANGELESCALONABUENO** [comment]
Hello, there, I wanted to ask if it is possible to use this part of the filament detector as an end stop for x axis, The reason why, it tells me that the end stop is activated all the time despite not having anything connected, the truth is that it is a board that I had lying there and it wouldn't seem strange to me if it is damaged, so I thought In two plans A to use the filament sensor and interpret it as end stop of x and B it would be to transfer the x to y and the y to z and buy a blt touch, do you see the first option as viable? The truth is I thought I had made a mistake with the pins but in reality I didn't.

![image](https://github.com/user-attachments/assets/2abce613-9226-44c9-8afd-9f2f36cdacbb)

**Comment by jonathanpere404** [comment]
Haven't been here in a while.
@aldi1502 You probably got it done, I guess. Anyway, this video has a good explanation of how to get started with Marlin installation on the board: https://www.youtube.com/watch?v=80IWoygNxB4
That video also explains how to get the BLTouch to work as an Z-axis sensor.

@yw4z For me, the filament sensor wasn't the best because when the filament runs out, the end tip of the filament is usually tilted.

![Image](https://github.com/user-attachments/assets/6cd9970d-0a12-4405-a819-5b12533b6f47)

The extruder motor is not powerful enough to pull it through. So the switch is always "ON," and it thinks that there is filament still. I think you're asking about the Z-axis end-point sensor.

![Image](https://github.com/user-attachments/assets/f9986ed6-3e1a-4052-91b5-5c13b44d8fb6)

So you want to install the "Klicky Probe" on it. Mine originally came with a "Klicky Probe," but I had some Chinese copy of an Ender 3. Actually, this was my original Z-axis sensor:

![Image](https://github.com/user-attachments/assets/6533adb4-c884-4e1a-9186-3411fe7b02f1)

It wasn't good because it has the metal spring thing, just not accurate enough. You can just follow the video but skip the BLTouch changes.

@ANGELESCALONABUENO I think your problem is this: if you use Marlin, there are options to change the signal type. "NO" = Normally Open, or "NC" = Normally Closed. You just change the "false" to "true" what ever axis you choose. Here’s an image of Marlin version 2.1.2.1. There might be a newer version, but i got the old one.

NO (Normally Open):

-In its default state, the circuit is open, meaning the electrical connection is broken, and no current flows.
-When the switch or relay is activated, the circuit closes, allowing current to flow.

NC (Normally Closed):

-In its default state, the circuit is closed, meaning the electrical connection is complete, and current flows.
-When the switch or relay is activated, the circuit opens, stopping the current.


![Image](https://github.com/user-attachments/assets/75a95972-3c46-41e7-9323-0fb274401546)

this is how my original printer looked like and how the z-axel sensor was (Voxelab Aquila C2), but i bought the board 4.2.7 for it. 

![Image](https://github.com/user-attachments/assets/4b007e12-0912-4b25-a514-830e02754fbb)

![Image](https://github.com/user-attachments/assets/32832d5f-def7-4a1a-9ff6-b342b2be9736)
